services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ${IMAGE}
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    # web слушает 8000 внутри контейнера (gunicorn)
    expose:
      - "8000"
    # если нужно, собираем статику на старте:
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn neptone.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - web_static:/app/staticfiles
      - web_media:/app/media

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "8000:80"              # наружу 8000 -> внутрь 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - web_static:/app/staticfiles:ro   # чтобы nginx видел собранную статику
      - web_media:/app/media:ro         # если используешь медиа
    restart: always


volumes:
  db_data:
  web_static:
  web_media: