# Generated by Django 5.1.7 on 2025-09-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_bio_alter_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
