# Generated by Django 5.1.7 on 2025-09-16 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_follow",
                "indexes": [
                    models.Index(
                        fields=["follower"], name="users_follo_followe_3a2483_idx"
                    ),
                    models.Index(
                        fields=["following"], name="users_follo_followi_e01def_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "following"),
                        name="uq_follow_follower_following",
                    )
                ],
            },
        ),
    ]
