# Generated by Django 5.1.7 on 2025-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
