name: Build & Deploy

on:
  pull_request:
    branches: ["dev"]        # PR в dev — проверочная сборка (без пуша)
  push:
    branches: ["main"]       # пуш в main — сборка + деплой

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE: ${{ steps.meta.outputs.IMAGE }}     # пробрасываем IMAGE в deploy
    steps:
      - uses: actions/checkout@v4

      # Логин в Docker Hub только на push (на PR секреты недоступны)
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        continue-on-error: true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          version: latest

      - name: Compute image tag (lowercase)
        id: meta
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LC}:latest" >> "$GITHUB_OUTPUT"

      - name: Build (push only on main)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Готовим бандл для копирования (исключаем пустые источники)
      - name: Prepare deploy bundle
        run: |
          set -euo pipefail
          rm -rf deploy_bundle
          mkdir -p deploy_bundle/nginx

          # docker-compose.prod.yml: сначала в корне, потом в docker/
          if [ -f "docker-compose.prod.yml" ]; then
            cp "docker-compose.prod.yml" "deploy_bundle/docker-compose.prod.yml"
          elif [ -f "docker/docker-compose.prod.yml" ]; then
            cp "docker/docker-compose.prod.yml" "deploy_bundle/docker-compose.prod.yml"
          else
            echo "ERROR: docker-compose.prod.yml not found in repo root or docker/"; exit 1
          fi

          # nginx.conf: в nginx/ или docker/nginx/
          if [ -f "nginx/nginx.conf" ]; then
            cp "nginx/nginx.conf" "deploy_bundle/nginx/nginx.conf"
          elif [ -f "docker/nginx/nginx.conf" ]; then
            cp "docker/nginx/nginx.conf" "deploy_bundle/nginx/nginx.conf"
          else
            echo "WARNING: nginx/nginx.conf not found; deploy will keep remote file if it exists"
          fi

          echo "== bundle tree =="
          find deploy_bundle -maxdepth 3 -type f -print

      # 2) Создаём каталоги на сервере
      - name: Ensure remote dirs
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -e
            mkdir -p /root/neptone/docker/nginx

      # 3) Копируем бандл
      - name: Upload deploy bundle via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "deploy_bundle/*"
          target: "/root/neptone/docker/"
          rm: true

      # 4) Деплой
      - name: Deploy over SSH (pull & up)
        uses: appleboy/ssh-action@v1.2.0
        env:
          IMAGE: ${{ needs.build.outputs.IMAGE }}   # экспортируем в шаг GH
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: IMAGE                                # <<< ПРОКИНУТЬ НА УДАЛЁННЫЙ ХОСТ
          script: |
            set -euo pipefail
            cd /root/neptone/docker

            echo "== IMAGE from CI =="
            echo "${IMAGE}"

            # .env для compose (секреты + тег образа)
            cat > .env <<ENVV
            ${{ secrets.ENV_PROD }}
            IMAGE=$IMAGE
            ENVV

            # Проверим, что IMAGE подставился
            if ! grep -qE '^IMAGE=.+$' .env; then
              echo "ERROR: IMAGE is empty in .env"; cat .env; exit 1
            fi

            # Диагностика
            ls -la
            [ -f nginx/nginx.conf ] && echo "nginx.conf present" || echo "nginx.conf MISSING"
            sha256sum docker-compose.prod.yml || true

            # Нормализация и валидация
            sed -i '1s/^\xEF\xBB\xBF//' docker-compose.prod.yml || true
            sed -i 's/\r$//' docker-compose.prod.yml || true
            sed -i 's/\t/  /g' docker-compose.prod.yml || true

            # Логины (GHCR обязателен; Hub — опционально)
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || true
            fi

            # Проверка финальной конфигурации
            docker compose --env-file .env -f docker-compose.prod.yml config | sed -n '/services:/,$p'

            # Обновление и запуск
            docker compose --env-file .env -f docker-compose.prod.yml pull
            docker compose --env-file .env -f docker-compose.prod.yml up -d

            docker system prune -f
