name: Build & Deploy

on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["main"]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE: ${{ steps.meta.outputs.IMAGE }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        continue-on-error: true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          version: latest

      - name: Compute image tag (lowercase)
        id: meta
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LC}:latest" >> "$GITHUB_OUTPUT"

      - name: Build (push only on main)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 0) На всякий случай: положим обновлённый compose в корень репо тоже
      - name: Ensure flattened compose in repo root (optional)
        run: |
          cp docker/docker-compose.prod.yml docker-compose.prod.yml

      # 1) Подготовить место на сервере и удалить кривые остатки
      - name: Prepare remote dir (cleanup)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -e
            mkdir -p /root/neptone/docker
            # удалить папку/файл, если вдруг есть с именем compose
            [ -d /root/neptone/docker/docker-compose.prod.yml ] && rm -rf /root/neptone/docker/docker-compose.prod.yml || true
            [ -f /root/neptone/docker/docker-compose.prod.yml ] && rm -f /root/neptone/docker/docker-compose.prod.yml || true
            # удалить старую папку nginx, раз теперь файл лежит в корне
            [ -d /root/neptone/docker/nginx ] && rm -rf /root/neptone/docker/nginx || true

      # 2) Копируем ОБА файла прямо в /root/neptone/docker/
      - name: Upload compose via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker/docker-compose.prod.yml"
          target: "/root/neptone/docker/"
          strip_components: 1
          overwrite: true

      - name: Upload nginx.conf via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker/nginx.conf"
          target: "/root/neptone/docker/"
          strip_components: 1
          overwrite: true

      # 3) Проверка на сервере, что оба файла лежат в КОРНЕ
      - name: Verify files on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd /root/neptone/docker
            echo "== listing =="
            ls -la
            [ -f docker-compose.prod.yml ] || (echo "docker-compose.prod.yml MISSING"; exit 1)
            [ -f nginx.conf ] || (echo "nginx.conf MISSING"; exit 1)

      # 4) Деплой
      - name: Deploy over SSH (pull & up)
        uses: appleboy/ssh-action@v1.2.0
        env:
          IMAGE: ${{ needs.build.outputs.IMAGE }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE
          script_stop: true
          script: |
            set -euo pipefail
            cd /root/neptone/docker

            echo "== IMAGE from CI =="
            echo "$IMAGE"

            # .env для compose
            cat > .env <<ENVV
            ${{ secrets.ENV_PROD }}
            IMAGE=$IMAGE
            ENVV

            # Нормализация и валидация
            sed -i '1s/^\xEF\xBB\xBF//' docker-compose.prod.yml || true
            sed -i 's/\r$//' docker-compose.prod.yml || true
            sed -i 's/\t/  /g' docker-compose.prod.yml || true

            # Логины
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || true
            fi

            # Проверка финальной конфигурации (у web должен быть image: ghcr.io/…)
            docker compose --env-file .env -f docker-compose.prod.yml config | sed -n '/services:/,$p'

            docker compose --env-file .env -f docker-compose.prod.yml pull
            docker compose --env-file .env -f docker-compose.prod.yml up -d

            # Check static
            docker compose --env-file .env -f docker-compose.prod.yml exec -T nginx \
              sh -lc 'ls -1 /app/staticfiles | head -n 5'

            docker system prune -f
