name: Build & Deploy

on:
  pull_request:
    branches: ["dev"]
  push:
    branches: ["main"]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE: ${{ steps.meta.outputs.IMAGE }}   # пробрасываем IMAGE в deploy
    steps:
      - uses: actions/checkout@v4

      # Логин в Docker Hub (чтобы не упираться в rate limit), делаем только на push
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        continue-on-error: true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          version: latest

      - name: Compute image tag (lowercase)
        id: meta
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LC}:latest" >> "$GITHUB_OUTPUT"

      - name: Build (push only on main)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Создаём директории на сервере под конфиги
      - name: Ensure remote dirs
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -e
            mkdir -p /root/neptone/docker/nginx

      # Копируем docker-compose.prod.yml ТОЧНО в нужный путь
      - name: Upload compose via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker/docker-compose.prod.yml"
          target: "/root/neptone/docker/docker-compose.prod.yml"
          overwrite: true

      # Копируем nginx.conf ТОЧНО в нужный путь
      - name: Upload nginx.conf via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker/nginx.conf"
          target: "/root/neptone/docker/nginx/nginx.conf"
          overwrite: true

      # Деплой
      - name: Deploy over SSH (pull & up)
        uses: appleboy/ssh-action@v1.2.0
        env:
          IMAGE: ${{ needs.build.outputs.IMAGE }}   # прокидываем из build
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE
          script_stop: true
          script: |
            set -euo pipefail
            cd /root/neptone/docker

            echo "== IMAGE from CI =="
            echo "$IMAGE"

            # .env для compose (секреты + тег образа)
            cat > .env <<ENVV
            ${{ secrets.ENV_PROD }}
            IMAGE=$IMAGE
            ENVV

            # Проверим, что всё на месте
            [ -f docker-compose.prod.yml ] || (echo "docker-compose.prod.yml MISSING"; exit 1)
            [ -f nginx/nginx.conf ] || (echo "nginx/nginx.conf MISSING"; exit 1)

            # Нормализация и валидация
            sed -i '1s/^\xEF\xBB\xBF//' docker-compose.prod.yml || true
            sed -i 's/\r$//' docker-compose.prod.yml || true
            sed -i 's/\t/  /g' docker-compose.prod.yml || true

            # Логин в реестры
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] && [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || true
            fi

            # Проверка финальной конфигурации (у web должен быть image: ghcr.io/...)
            docker compose --env-file .env -f docker-compose.prod.yml config | sed -n '/services:/,$p'

            # Обновление и запуск
            docker compose --env-file .env -f docker-compose.prod.yml pull
            docker compose --env-file .env -f docker-compose.prod.yml up -d

            docker system prune -f
